### ISSUE TITLE
Unable to add "Allowed Fact Modules" for the first time

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [ctrliq/ascender-ledger#14]
On a fresh installation of Ledger,
1. Visit https://ledger.your.domain/settings/
2. Attempt to populate the **Allowed Fact Modules** field

We came across this during a Zoom with @michaelford85 and @cigamit but I forgot to submit a bug.

**Comment by adamhgriffith-uofu** [comment]
As @cigamit mentioned, the work-around for now is to:
```console
$ kubectl exec -it db-7fcdb9c9bf-52lxh -n ledger -- bash
[root@db-7fcdb9c9bf-52lxh /]# mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 548
Server version: 10.5.16-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use ledger;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [ledger]> insert into settings (setting,value) values ("allowed_modules", "gather_facts");
Query OK, 1 row affected (0.001 sec)

MariaDB [ledger]> exit;
Bye
```

**Comment by adamhgriffith-uofu** [comment]
Was not able to reproduce this issue on a recent installation of Ascender/Ledger. Doesn't appear that anything has changed in the Ledger code so maybe gremlins?

**Comment by adamhgriffith-uofu** [comment]
A coworker was playing with a fresh Ascender/Ledger installation and was able to reproduce. Weird.

**Comment by cigamit** [comment]
Ok, let me fire up a fresh install and test a few things.

**Comment by cigamit** [comment]
This is now fixed.  There was an issue in the db upgrade script that was causing it to fail during the upgrade process stopping it from adding our default value.  I also added a fix in the settings to account for installs that have already been upgraded but still fail.  I will push out a new version shortly, you should be able to do a rolling restart of your ledger deployment and it will pull the new version.
